### ISSUE TITLE
登录好麻烦

### ISSUE THREAD

**Issue by jjsisjjz** [KaiserLancelot/kepub#1]
爬完一本就要重新登录

**Comment by KaiserLancelot** [comment]
暂时没有时间增添功能.将在未来支持保存登陆状态,批量爬取等功能.欢迎发起PR

**Comment by jjsisjjz** [comment]
sf的爬不了

**Comment by jjsisjjz** [comment]
sf的好像没用

**Comment by KaiserLancelot** [comment]
昨天提交了一些代码，可以保存登陆状态了，还没改完，主线可能不能正常运行。v0.8.1应该没问题，昨天下午还用了一次。

**Comment by KaiserLancelot** [comment]
如果v0.8.1也不好使，请提供输入和错误信息

**Comment by KaiserLancelot** [comment]
v0.9.0已发布,保存登陆状态已可用,sfacg错误已修正

**Comment by jjsisjjz** [comment]
每次都要把cookie文件删了才能登陆其他账号

**Comment by KaiserLancelot** [comment]
与多账号相关的功能不打算支持
