### ISSUE TITLE
Ciweimao added geetest CAPTCHA to the login api in version 2.9.290

### ISSUE THREAD

**Issue by RujiaZhang** [KaiserLancelot/kepub#10]
Here is the Burp Suite result:

> POST /signup/login HTTP/2
> Host: app.hbooker.com
> User-Agent: Android  com.kuangxiangciweimao.novel  2.9.290, [REDACTED]
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 240
> Accept-Encoding: gzip, deflate
> 
> geetest_seccode=[REDACTED]%7Cjordan&login_name=[REDACTED]&geetest_validate=[REDACTED]&app_version=2.9.290&passwd=[REDACTED]&device_token=ciweimao_&geetest_challenge=[REDACTED]

Although the API of 2.9.282 can still be used normally, I don't think it will never fail. Is there any solution? Let the user directly enter the login_token obtained from the APP (requires root), or try to simulate CAPTCHA on the computer?

**Comment by KaiserLancelot** [comment]
I also noticed this problem and I found a solution on GitHub [[1]](https://github.com/Amovane/GeetestReverseEngineering), but there is still a lot of work to be done:

- Verify the feasibility of the solution
- Explore whether the solution can be implemented in C++ or Rust
- Do not create external dependencies as much as possible

This will take some time, but I think it can be done before the old version becomes unusable

@RujiaZhang

**Comment by RujiaZhang** [comment]
@KaiserLancelot 
I've sent an email to you. Please check your gmail box, thx.
