### ISSUE TITLE
hi，what should i do

### ISSUE THREAD

**Issue by EliasMercer** [KaiserLancelot/kepub#12]
i am a rookie in this respect
![1](https://user-images.githubusercontent.com/90075518/176662534-53996783-e0b1-4445-8cb9-da7b0fd611e8.png)
![2](https://user-images.githubusercontent.com/90075518/176662810-6effbed4-c85a-4e17-b8bb-ada2652bb944.png)

**Comment by KaiserLancelot** [comment]
Your glibc version is too old, you need to change to a newer OS, such as Ubuntu 20.04
@EliasMercer

**Comment by KaiserLancelot** [comment]
You can also use docker or compile it yourself
