### ISSUE TITLE
[help wanted] Does this app help downloading SF Vip chapters?

### ISSUE THREAD

**Issue by AlexanderHel** [KaiserLancelot/kepub#4]
Hi, I'm trying to find a way to downloading SF Vip chapters to text format ( I already purchased the chapters ), I stumbled this repo while google search.
Cause I'm reading Chinese Novel using Google Translate so I can't read the Vip one due to their being images.

Regard.

**Comment by KaiserLancelot** [comment]
@AlexanderHel 
Of course, the program can download VIP chapters. Unpurchased chapters are automatically skipped when downloading.

**Comment by KaiserLancelot** [comment]
@AlexanderHel 
Note that this program has only been tested on Ubuntu and WSL2. After installing the deb package, use the bookid to download

**Comment by AlexanderHel** [comment]
> @AlexanderHel Note that this program has only been tested on Ubuntu and WSL2. After installing the deb package, use the bookid to download

Hi, sorry but do you have a guide how to use this program? I managed to install it on Debian 11 but it show as add-on and I don't know how to run it 
I'm not familiar with linux sorry, only using window so far

**Comment by KaiserLancelot** [comment]
> > @AlexanderHel Note that this program has only been tested on Ubuntu and WSL2. After installing the deb package, use the bookid to download
> 
> Hi, sorry but do you have a guide how to use this program? I managed to install it on Debian 11 but it show as add-on and I don't know how to run it I'm not familiar with linux sorry, only using window so far

- First, install the deb package

   ```bash
   sudo dpkg -i kepub-0.15.9-Linux.deb
   ````

- After installation, run:

   ```bash
   sfacg -v
   ````

   You will see version information.

- Take this book as an example: https://book.sfacg.com/Novel/208551, whose bookid is **208551**, run:

   ```bash
   sfacg 208551
   ````

   Enter your username and password to start downloading.

- If there are any errors, please provide complete error information.

**Comment by AlexanderHel** [comment]
When I ran
`sfacg -v`

I got :"Illegal Instruction"

Screenshot: https://prnt.sc/26ss4q6

**Comment by KaiserLancelot** [comment]
> When I ran `sfacg -v`
> 
> I got :"Illegal Instruction"
> 
> Screenshot: https://prnt.sc/26ss4q6

This was indeed a problem because the program and dependent libraries were compiled with the compile parameter '-march=haswell', which caused it not to run on older CPUs.
What is your CPU please?

**Comment by KaiserLancelot** [comment]
@AlexanderHel 
I'm not quite sure if this program can run on relatively new AMD CPUs. Is your CPU an AMD Zen?

**Comment by AlexanderHel** [comment]
> @AlexanderHel I'm not quite sure if this program can run on relatively new AMD CPUs. Is your CPU an AMD Zen?

Oh damn, I running Debian 11 on Virtual Box maybe it is the reason

**Comment by KaiserLancelot** [comment]
> > @AlexanderHel I'm not quite sure if this program can run on relatively new AMD CPUs. Is your CPU an AMD Zen?
> 
> Oh damn, I running Debian 11 on Virtual Box maybe it is the reason

I'm not familiar with Virtual Box and can't be sure if this is the cause. Since you're using Windows, try using WSL2, and if the problem resolves, then you can be sure it's a virtual machine problem.

**Comment by AlexanderHel** [comment]
> > > @AlexanderHel I'm not quite sure if this program can run on relatively new AMD CPUs. Is your CPU an AMD Zen?
> > 
> > 
> > Oh damn, I running Debian 11 on Virtual Box maybe it is the reason
> 
> I'm not familiar with Virtual Box and can't be sure if this is the cause. Since you're using Windows, try using WSL2, and if the problem resolves, then you can be sure it's a virtual machine problem.

Thanks, I will looking for WSL2 and let you know

**Comment by AlexanderHel** [comment]
> > > @AlexanderHel I'm not quite sure if this program can run on relatively new AMD CPUs. Is your CPU an AMD Zen?
> > 
> > 
> > Oh damn, I running Debian 11 on Virtual Box maybe it is the reason
> 
> I'm not familiar with Virtual Box and can't be sure if this is the cause. Since you're using Windows, try using WSL2, and if the problem resolves, then you can be sure it's a virtual machine problem.

Thank you very much, by using WSL2, now the program working flawlessly https://prnt.sc/26tsm0j
Hope you can add function to download selected chapter or link so don't have to download whole novel every time

**Comment by KaiserLancelot** [comment]
> > > > @AlexanderHel I'm not quite sure if this program can run on relatively new AMD CPUs. Is your CPU an AMD Zen?
> > > 
> > > 
> > > Oh damn, I running Debian 11 on Virtual Box maybe it is the reason
> > 
> > 
> > I'm not familiar with Virtual Box and can't be sure if this is the cause. Since you're using Windows, try using WSL2, and if the problem resolves, then you can be sure it's a virtual machine problem.
> 
> Thank you very much, by using WSL2, now the program working flawlessly https://prnt.sc/26tsm0j Hope you can add function to download selected chapter or link so don't have to download whole novel every time

Hope you have a pleasant reading experience.
But I don't have time to add a new feature right now. When I get the time (maybe in a few months), I'll try to support it.

**Comment by AlexanderHel** [comment]
> @AlexanderHel If you want to download the entire novel, are you satisfied with the download speed? Do you need multi-threading to speed up the download?

The novel I downloaded not big but I think the speed is all good, but ofc if it can improve I will gladly take it, you can improve it when you have free time
For now I'm pretty satisfied with it
