### ISSUE TITLE
Ciweimao bug on latest version

### ISSUE THREAD

**Issue by AlexanderHel** [KaiserLancelot/kepub#6]
Ciweimao not working but sfacg still fine

![image](https://user-images.githubusercontent.com/99399435/159150966-224d8698-4633-4cbc-819c-8402ae0183ee.png)

I reverted to 2.0.0 and download smoothly 

![image](https://user-images.githubusercontent.com/99399435/159150993-d71ee49e-c85b-437a-9e16-ecc6a80a0587.png)

**Comment by KaiserLancelot** [comment]
I'm guessing, this is not a bug.
Since the new version has changed the encryption algorithm for saving the login information, there is a problem when reading the information of the old version.
try to run
```bash
rm /tmp/ciweimao
```
the problem should be resolved 

@AlexanderHel

**Comment by AlexanderHel** [comment]
> ```shell
> rm /tmp/ciweimao
> ```

Thank you, it's working now
I think after changing the encryption you should make the program run that command and asking for login information again

**Comment by KaiserLancelot** [comment]
> > ```shell
> > rm /tmp/ciweimao
> > ```
> 
> Thank you, it's working now I think after changing the encryption you should make the program run that command and asking for login information again

This is a good idea.

**Comment by KaiserLancelot** [comment]
solved
