### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by KaiserLancelot** [KaiserLancelot/kepub#7]
If you have time, please try the latest version to see if the bug is fixed.
@Hitlesama

**Comment by Hitlesama** [comment]
Okay, I just tried it with the most recent version, and the issue has been resolved. If Kepub releases a new version, I might be the one to help you locate the error haha.
@KaiserLancelot

**Comment by KaiserLancelot** [comment]
> Okay, I just tried it with the most recent version, and the issue has been resolved. If Kepub releases a new version, I might be the one to help you locate the error haha. @KaiserLancelot

👍

**Comment by Hitlesama** [comment]
Hi KaiserLancelot, I just noticed that there was some sort of issue on Ciweimao, huh?

**Comment by KaiserLancelot** [comment]
> Hi KaiserLancelot, I just noticed that there was some sort of issue on Ciweimao, huh?

has been fixed in the latest version

**Comment by Hitlesama** [comment]
I saw the lastest version, but is it a sign that Ciweimao is attempting to block us from obtaining the text? If so, I am very nervous now ~~.

**Comment by KaiserLancelot** [comment]
> I saw the lastest version, but is it a sign that Ciweimao is attempting to block us from obtaining the text? If so, I am very nervous now ~~.

Yes, the authentication method has changed on the iOS side this week, but the Android side has not changed yet. Once the Android side changes, I will crack it in a few days

**Comment by Hitlesama** [comment]
UwU, You're so intelligent and brilliant, which just adds to my respect and admiration for your efforts :D. Once again, thank you for your assistance; we couldn't read it without you. In the future, I wish you continued success in this field.
