### ISSUE TITLE
Can't log in account ciweimao to download txt

### ISSUE THREAD

**Issue by Hitlesama** [KaiserLancelot/kepub#9]
![image](https://user-images.githubusercontent.com/101611167/170861644-79602018-73aa-42fd-bccd-772a739ccb3e.png)

**Comment by KaiserLancelot** [comment]
> ![image](https://user-images.githubusercontent.com/101611167/170861644-79602018-73aa-42fd-bccd-772a739ccb3e.png)

ciweimao's interface validation changed, I'll try to fix it at night

**Comment by KaiserLancelot** [comment]
I found that this does not seem to be my problem. You can try to reset the password in the APP, and then try to log in to ciweimao, the problem should be solved
@Hitlesama

**Comment by Hitlesama** [comment]
![image](https://user-images.githubusercontent.com/101611167/172001692-e3ef13fd-475e-4b11-9860-3d0a33747c95.png)
:((( It happend again

**Comment by Hitlesama** [comment]
I just reinstall ubuntu and update latest version then I gonna log acc ciweimao and as you see

**Comment by Hitlesama** [comment]
@KaiserLancelot

**Comment by KaiserLancelot** [comment]
> [2022-06-04 21:40:52.862] [error] [json.cpp:200] 此书可能已下架16

You are using an environment that does not display Chinese, and the actual error message is as above: The book has been taken down.
ciweimao has taken down a lot of novels in the past few days.

@Hitlesama

**Comment by KaiserLancelot** [comment]
There seems to be a problem with your login as well, which I can't reproduce here. ciweimao seems to be having a lot of glitches these days, please make sure you can log in on the app side.

**Comment by Hitlesama** [comment]
Oh, I I'm still logged in on the app and [json.cpp:177] 用户名或密码错误 , so I don`t know why it happen again. Few days ago, when I reinstall unbuntu and log in to download txt, it worked. But now, I used the same way and it notice log in failed :(
@KaiserLancelot

**Comment by KaiserLancelot** [comment]
> Oh, I'm still logged in on the app and [json.cpp:177] 用户名或密码错误 , so I don`t know why it happens again. Few days ago, when I reinstall unbuntu and log in to download txt, it worked. But now, I used the same way and it notice log in failed :( @KaiserLancelot

You try to log in the APP side, you can log in normally?

**Comment by Hitlesama** [comment]
Yes, I log in normally on the app ciweimao

**Comment by KaiserLancelot** [comment]
> Yes, I log in normally on the app ciweimao

Make sure you are using the latest version of kepub first.
If you still can't log in, I don't know how to handle it, I can't reproduce the problem.

**Comment by Hitlesama** [comment]
OMG, did you use ultraview ? Can you help me check my computer what's wrong
with it?

Vào Th 7, 4 thg 6, 2022 vào lúc 21:14 Kaiser ***@***.***>
đã viết:

**Comment by KaiserLancelot** [comment]
> OMG, did you use ultraview ? Can you help me check my computer what's wrong with it?

I don't use it. And I'm afraid I can't help you check your computer's problems

**Comment by Hitlesama** [comment]
Do you know how to reset pass ciweimao through pass present ? Not rest
through foget pass

**Comment by KaiserLancelot** [comment]
> Do you know how to reset pass ciweimao through pass present ? Not rest through foget pass
> […](#)
> Message ID: ***@***.***>

It seems that the password can only be changed by 'forgot password'

**Comment by Hitlesama** [comment]
okay tks, I just reset pass and fortunately, it worked again :D

Vào Th 7, 4 thg 6, 2022 vào lúc 21:45 Kaiser ***@***.***>
đã viết:

**Comment by Hitlesama** [comment]
Could you take txt book which has been taken down ?

**Comment by KaiserLancelot** [comment]
> Could you take txt book which has been taken down ?

Unfortunately, this is not possible.
